 CC= g++
 CFLAGS= -Wall -Wextra -g
 DEPS = $(wildcard *.h)
# %.out: %.cpp $(DEPS)
# 	$(CC) -c -o $@ $< $(CFLAGS)
all: 	
		g++ main.cpp -o main.out



# main.o: main.cpp
# 	g++ -c main.cpp
clean: 
		rm -rf *o main.out